services:
  postgres:
    image: postgres:18.4
    container_name: knot-postgres

    environment:
      POSTGRES_DB: knot
      POSTGRES_USER: knot
      POSTGRES_PASSWORD: knot

    ports:
      - "5432:5432"

    volumes:
      - knot-postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knot -d knot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  knot-postgres-data:
