server {
    listen 127.0.0.1:3001;
    server_name localhost;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host 127.0.0.1:33000;
        proxy_set_header X-Knot-Viewer knot-viewer;
        proxy_set_header X-Forwarded-Proto http;
    }
}
