ALTER TABLE content_import_runs
    ADD CONSTRAINT uk_content_import_runs_id_workspace UNIQUE (id, workspace_id);

ALTER TABLE content_import_runs
    ADD CONSTRAINT uk_content_import_runs_id_workspace_status UNIQUE (id, workspace_id, status);

CREATE TABLE imported_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    import_run_id BIGINT NOT NULL,
    external_page_id VARCHAR(100) NOT NULL,
    parent_external_page_id VARCHAR(100),
    title TEXT NOT NULL,
    markdown_content TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    source_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_imported_pages PRIMARY KEY (id),
    CONSTRAINT uk_imported_pages_workspace_run_external_page
        UNIQUE (workspace_id, import_run_id, external_page_id),
    CONSTRAINT uk_imported_pages_id_workspace_run UNIQUE (id, workspace_id, import_run_id),
    CONSTRAINT fk_imported_pages_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_imported_pages_import_run
        FOREIGN KEY (import_run_id, workspace_id)
        REFERENCES content_import_runs (id, workspace_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_imported_pages_parent
        FOREIGN KEY (workspace_id, import_run_id, parent_external_page_id)
        REFERENCES imported_pages (workspace_id, import_run_id, external_page_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_imported_pages_external_page_id
        CHECK (BTRIM(external_page_id) <> ''),
    CONSTRAINT chk_imported_pages_parent
        CHECK (parent_external_page_id IS NULL OR parent_external_page_id <> external_page_id),
    CONSTRAINT chk_imported_pages_position
        CHECK (position >= 0),
    CONSTRAINT chk_imported_pages_source_url
        CHECK (BTRIM(source_url) <> ''),
    CONSTRAINT chk_imported_pages_timestamps
        CHECK (updated_at >= created_at)
);

CREATE TABLE imported_page_publications (
    workspace_id BIGINT NOT NULL,
    published_import_run_id BIGINT NOT NULL,
    published_import_status VARCHAR(10) NOT NULL DEFAULT 'COMPLETED',
    published_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_imported_page_publications PRIMARY KEY (workspace_id),
    CONSTRAINT chk_imported_page_publications_status
        CHECK (published_import_status = 'COMPLETED'),
    CONSTRAINT fk_imported_page_publications_import_run
        FOREIGN KEY (published_import_run_id, workspace_id, published_import_status)
        REFERENCES content_import_runs (id, workspace_id, status)
        ON DELETE RESTRICT
);

CREATE INDEX idx_imported_pages_workspace_run_order
    ON imported_pages (workspace_id, import_run_id, position, id);
