CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE search_document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    import_run_id BIGINT NOT NULL,
    imported_page_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1024) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_search_document_chunks PRIMARY KEY (id),
    CONSTRAINT uk_search_document_chunks_workspace_run_page_chunk
        UNIQUE (workspace_id, import_run_id, imported_page_id, chunk_index),
    CONSTRAINT fk_search_document_chunks_page
        FOREIGN KEY (imported_page_id, workspace_id, import_run_id)
        REFERENCES imported_pages (id, workspace_id, import_run_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_search_document_chunks_chunk_index
        CHECK (chunk_index >= 0),
    CONSTRAINT chk_search_document_chunks_content
        CHECK (BTRIM(content) <> '')
);

CREATE INDEX idx_search_document_chunks_workspace_run
    ON search_document_chunks (workspace_id, import_run_id, imported_page_id, chunk_index);

CREATE INDEX idx_search_document_chunks_embedding_hnsw
    ON search_document_chunks USING hnsw (embedding vector_cosine_ops);

CREATE TABLE search_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL,
    import_run_id BIGINT NOT NULL,
    imported_page_id BIGINT NOT NULL,
    reference_rank SMALLINT NOT NULL,
    relevance_score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_search_references PRIMARY KEY (id),
    CONSTRAINT uk_search_references_message_rank UNIQUE (message_id, reference_rank),
    CONSTRAINT uk_search_references_message_page UNIQUE (message_id, imported_page_id),
    CONSTRAINT fk_search_references_message
        FOREIGN KEY (message_id)
        REFERENCES chat_messages (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_search_references_page
        FOREIGN KEY (imported_page_id, workspace_id, import_run_id)
        REFERENCES imported_pages (id, workspace_id, import_run_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_search_references_rank
        CHECK (reference_rank BETWEEN 1 AND 3),
    CONSTRAINT chk_search_references_relevance
        CHECK (relevance_score >= 0 AND relevance_score <= 1)
);

CREATE INDEX idx_search_references_message_rank
    ON search_references (message_id, reference_rank);
