-- 데스크톱 2단계 인증(기획서 5.2, 로드맵 A6).
-- device_sessions: 기기 로그인 1건. 세션 id가 액세스 토큰의 sid 클레임이자 기기 목록·폐기 API의 공개 id다.
-- device_refresh_tokens: 세션당 현재 토큰 1개(rotated_at IS NULL). rotation마다 새 행을 만들고 이전 행은 rotated_at을 채워
--   재사용 감지에 쓴다(RFC 9700 §4.14.2). DB에는 SHA-256 해시만 둔다.
-- device_authorization_codes: 시스템 브라우저 → 앱 일회용 코드(TTL 120초, S256 challenge 바인딩). 기존 회원이면 member_id,
--   닉네임을 아직 정하지 않은 사용자면 OAuth 식별 정보를 담아 교환 시 온보딩 토큰을 발급한다.

CREATE TABLE device_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    app_version VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_device_sessions PRIMARY KEY (id),
    CONSTRAINT fk_device_sessions_member
        FOREIGN KEY (member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_device_sessions_device_name
        CHECK (btrim(device_name) <> ''),
    CONSTRAINT chk_device_sessions_platform
        CHECK (btrim(platform) <> ''),
    CONSTRAINT chk_device_sessions_app_version
        CHECK (app_version IS NULL OR btrim(app_version) <> ''),
    CONSTRAINT chk_device_sessions_last_used_at
        CHECK (last_used_at >= created_at),
    CONSTRAINT chk_device_sessions_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_device_sessions_member_active
    ON device_sessions (member_id, last_used_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE device_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    rotated_at TIMESTAMPTZ,
    CONSTRAINT pk_device_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uk_device_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_device_refresh_tokens_session
        FOREIGN KEY (session_id)
        REFERENCES device_sessions (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_device_refresh_tokens_token_hash
        CHECK (btrim(token_hash) <> ''),
    CONSTRAINT chk_device_refresh_tokens_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT chk_device_refresh_tokens_rotated_at
        CHECK (rotated_at IS NULL OR rotated_at >= created_at)
);

CREATE UNIQUE INDEX uk_device_refresh_tokens_one_current
    ON device_refresh_tokens (session_id)
    WHERE rotated_at IS NULL;

CREATE TABLE device_authorization_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code_hash VARCHAR(64) NOT NULL,
    code_challenge VARCHAR(128) NOT NULL,
    member_id BIGINT,
    oauth_provider VARCHAR(20),
    oauth_provider_user_id VARCHAR(255),
    oauth_profile_image_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    consumed_session_id BIGINT,
    CONSTRAINT pk_device_authorization_codes PRIMARY KEY (id),
    CONSTRAINT uk_device_authorization_codes_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_device_authorization_codes_member
        FOREIGN KEY (member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_device_authorization_codes_session
        FOREIGN KEY (consumed_session_id)
        REFERENCES device_sessions (id)
        ON DELETE SET NULL,
    CONSTRAINT chk_device_authorization_codes_code_hash
        CHECK (btrim(code_hash) <> ''),
    CONSTRAINT chk_device_authorization_codes_code_challenge
        CHECK (btrim(code_challenge) <> ''),
    CONSTRAINT chk_device_authorization_codes_subject
        CHECK (
            (member_id IS NOT NULL
                AND oauth_provider IS NULL
                AND oauth_provider_user_id IS NULL
                AND oauth_profile_image_url IS NULL)
            OR (member_id IS NULL
                AND oauth_provider IS NOT NULL
                AND btrim(oauth_provider) <> ''
                AND oauth_provider_user_id IS NOT NULL
                AND btrim(oauth_provider_user_id) <> '')
        ),
    CONSTRAINT chk_device_authorization_codes_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT chk_device_authorization_codes_consumed_at
        CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_device_authorization_codes_expires_at
    ON device_authorization_codes (expires_at);
