CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_workspaces PRIMARY KEY (id),
    CONSTRAINT chk_workspaces_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE workspace_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_workspace_members PRIMARY KEY (id),
    CONSTRAINT uk_workspace_members_workspace_member UNIQUE (workspace_id, member_id),
    CONSTRAINT fk_workspace_members_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_workspace_members_member_id_positive CHECK (member_id > 0),
    CONSTRAINT chk_workspace_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE INDEX idx_workspace_members_member
    ON workspace_members (member_id);
