CREATE TABLE workspace_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    link_token_hash VARCHAR(255) NOT NULL,
    invite_code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    invalidated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_workspace_invitations PRIMARY KEY (id),
    CONSTRAINT uk_workspace_invitations_link_token_hash UNIQUE (link_token_hash),
    CONSTRAINT uk_workspace_invitations_invite_code_hash UNIQUE (invite_code_hash),
    CONSTRAINT fk_workspace_invitations_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_workspace_invitations_expiration CHECK (expires_at > created_at),
    CONSTRAINT chk_workspace_invitations_invalidation
        CHECK (invalidated_at IS NULL OR invalidated_at >= created_at)
);

CREATE UNIQUE INDEX uk_workspace_invitations_one_uninvalidated
    ON workspace_invitations (workspace_id)
    WHERE invalidated_at IS NULL;
