CREATE TABLE chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    title VARCHAR(255) DEFAULT '새 대화' NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    last_message_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_chat_sessions PRIMARY KEY (id),

    CONSTRAINT fk_chat_sessions_workspace_member
        FOREIGN KEY (workspace_id, member_id)
        REFERENCES workspace_members (workspace_id, member_id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_chat_sessions_workspace_id_positive CHECK (workspace_id > 0),
    CONSTRAINT chk_chat_sessions_member_id_positive CHECK (member_id > 0),
    CONSTRAINT chk_chat_sessions_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_chat_sessions_created_at_before_last_message
        CHECK (created_at <= last_message_at)
);

CREATE INDEX idx_chat_sessions_workspace_member_last_message
    ON chat_sessions (workspace_id, member_id, last_message_at DESC, id DESC);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_chat_messages PRIMARY KEY (id),

    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id)
        REFERENCES chat_sessions (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_chat_messages_session_id_positive CHECK (session_id > 0),
    CONSTRAINT chk_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT chk_chat_messages_content_not_blank CHECK (btrim(content) <> '')
);

CREATE INDEX idx_chat_messages_session_created_at
    ON chat_messages (session_id, created_at ASC, id ASC);

CREATE TABLE chat_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    result VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_chat_feedback PRIMARY KEY (id),

    CONSTRAINT fk_chat_feedback_message
        FOREIGN KEY (message_id)
        REFERENCES chat_messages (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_chat_feedback_member
        FOREIGN KEY (member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_chat_feedback_message_member UNIQUE (message_id, member_id),
    CONSTRAINT chk_chat_feedback_message_id_positive CHECK (message_id > 0),
    CONSTRAINT chk_chat_feedback_member_id_positive CHECK (member_id > 0),
    CONSTRAINT chk_chat_feedback_result CHECK (result IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX idx_chat_feedback_message
    ON chat_feedback (message_id);
