CREATE TABLE content_source_authorizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    authorizing_member_id BIGINT NOT NULL,
    state_hash VARCHAR(255) NOT NULL,
    callback_uri VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    invalidated_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_content_source_authorizations PRIMARY KEY (id),
    CONSTRAINT uk_content_source_authorizations_state_hash UNIQUE (state_hash),
    CONSTRAINT fk_content_source_authorizations_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_content_source_authorizations_member
        FOREIGN KEY (authorizing_member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_content_source_authorizations_provider
        CHECK (provider IN ('NOTION')),
    CONSTRAINT chk_content_source_authorizations_state_hash
        CHECK (btrim(state_hash) <> ''),
    CONSTRAINT chk_content_source_authorizations_callback_uri
        CHECK (btrim(callback_uri) <> ''),
    CONSTRAINT chk_content_source_authorizations_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT chk_content_source_authorizations_consumed_at
        CHECK (consumed_at IS NULL OR consumed_at >= created_at),
    CONSTRAINT chk_content_source_authorizations_invalidated_at
        CHECK (invalidated_at IS NULL OR invalidated_at >= created_at)
);

CREATE UNIQUE INDEX uk_content_source_authorizations_one_pending
    ON content_source_authorizations (workspace_id, provider)
    WHERE consumed_at IS NULL AND invalidated_at IS NULL;

CREATE INDEX idx_content_source_authorizations_workspace_provider_id
    ON content_source_authorizations (workspace_id, provider, id);

CREATE TABLE content_source_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    access_credential_ciphertext VARCHAR(1024) NOT NULL,
    refresh_credential_ciphertext VARCHAR(1024),
    external_source_id VARCHAR(255) NOT NULL,
    external_source_name VARCHAR(255),
    external_source_icon VARCHAR(2048),
    provider_connection_id VARCHAR(255) NOT NULL,
    authorization_owner_type VARCHAR(32) NOT NULL,
    authorization_owner_id VARCHAR(255),
    external_template_id VARCHAR(255),
    provider_request_id VARCHAR(255),
    authorizing_member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_content_source_connections PRIMARY KEY (id),
    CONSTRAINT uk_content_source_connections_workspace_provider
        UNIQUE (workspace_id, provider),
    CONSTRAINT fk_content_source_connections_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_content_source_connections_member
        FOREIGN KEY (authorizing_member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_content_source_connections_provider
        CHECK (provider IN ('NOTION')),
    CONSTRAINT chk_content_source_connections_access_credential
        CHECK (btrim(access_credential_ciphertext) <> ''),
    CONSTRAINT chk_content_source_connections_refresh_credential
        CHECK (refresh_credential_ciphertext IS NULL OR btrim(refresh_credential_ciphertext) <> ''),
    CONSTRAINT chk_content_source_connections_external_source_id
        CHECK (btrim(external_source_id) <> ''),
    CONSTRAINT chk_content_source_connections_external_source_name
        CHECK (external_source_name IS NULL OR btrim(external_source_name) <> ''),
    CONSTRAINT chk_content_source_connections_external_source_icon
        CHECK (external_source_icon IS NULL OR btrim(external_source_icon) <> ''),
    CONSTRAINT chk_content_source_connections_provider_connection_id
        CHECK (btrim(provider_connection_id) <> ''),
    CONSTRAINT chk_content_source_connections_authorization_owner
        CHECK (
            (authorization_owner_type = 'USER'
                AND authorization_owner_id IS NOT NULL
                AND btrim(authorization_owner_id) <> '')
            OR (authorization_owner_type = 'WORKSPACE' AND authorization_owner_id IS NULL)
        ),
    CONSTRAINT chk_content_source_connections_external_template_id
        CHECK (external_template_id IS NULL OR btrim(external_template_id) <> ''),
    CONSTRAINT chk_content_source_connections_provider_request_id
        CHECK (provider_request_id IS NULL OR btrim(provider_request_id) <> ''),
    CONSTRAINT chk_content_source_connections_updated_at
        CHECK (updated_at >= created_at)
);
