CREATE TABLE notion_oauth_authorizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    authorizing_member_id BIGINT NOT NULL,
    state_hash VARCHAR(255) NOT NULL,
    callback_uri VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    invalidated_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_notion_oauth_authorizations PRIMARY KEY (id),
    CONSTRAINT uk_notion_oauth_authorizations_state_hash UNIQUE (state_hash),
    CONSTRAINT fk_notion_oauth_authorizations_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notion_oauth_authorizations_authorizing_member
        FOREIGN KEY (authorizing_member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notion_oauth_authorizations_state_hash_not_blank CHECK (btrim(state_hash) <> ''),
    CONSTRAINT chk_notion_oauth_authorizations_callback_uri_not_blank CHECK (btrim(callback_uri) <> ''),
    CONSTRAINT chk_notion_oauth_authorizations_expiration CHECK (expires_at > created_at),
    CONSTRAINT chk_notion_oauth_authorizations_consumed_at
        CHECK (consumed_at IS NULL OR consumed_at >= created_at),
    CONSTRAINT chk_notion_oauth_authorizations_invalidated_at
        CHECK (invalidated_at IS NULL OR invalidated_at >= created_at)
);

CREATE UNIQUE INDEX uk_notion_oauth_authorizations_one_pending
    ON notion_oauth_authorizations (workspace_id)
    WHERE consumed_at IS NULL AND invalidated_at IS NULL;

CREATE INDEX idx_notion_oauth_authorizations_workspace_id_id
    ON notion_oauth_authorizations (workspace_id, id);

CREATE TABLE notion_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    access_token_ciphertext VARCHAR(1024) NOT NULL,
    refresh_token_ciphertext VARCHAR(1024),
    notion_workspace_id VARCHAR(255) NOT NULL,
    notion_workspace_name VARCHAR(255),
    notion_workspace_icon VARCHAR(2048),
    bot_id VARCHAR(255) NOT NULL,
    owner_type VARCHAR(32) NOT NULL,
    owner_user_id VARCHAR(255),
    duplicated_template_id VARCHAR(255),
    request_id VARCHAR(255),
    authorizing_member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_notion_connections PRIMARY KEY (id),
    CONSTRAINT uk_notion_connections_workspace UNIQUE (workspace_id),
    CONSTRAINT fk_notion_connections_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notion_connections_authorizing_member
        FOREIGN KEY (authorizing_member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notion_connections_access_token_ciphertext_not_blank
        CHECK (btrim(access_token_ciphertext) <> ''),
    CONSTRAINT chk_notion_connections_refresh_token_ciphertext_not_blank
        CHECK (refresh_token_ciphertext IS NULL OR btrim(refresh_token_ciphertext) <> ''),
    CONSTRAINT chk_notion_connections_notion_workspace_id_not_blank
        CHECK (btrim(notion_workspace_id) <> ''),
    CONSTRAINT chk_notion_connections_notion_workspace_name_not_blank
        CHECK (notion_workspace_name IS NULL OR btrim(notion_workspace_name) <> ''),
    CONSTRAINT chk_notion_connections_notion_workspace_icon_not_blank
        CHECK (notion_workspace_icon IS NULL OR btrim(notion_workspace_icon) <> ''),
    CONSTRAINT chk_notion_connections_bot_id_not_blank CHECK (btrim(bot_id) <> ''),
    CONSTRAINT chk_notion_connections_owner
        CHECK (
            (owner_type = 'user' AND owner_user_id IS NOT NULL AND btrim(owner_user_id) <> '')
            OR (owner_type = 'workspace' AND owner_user_id IS NULL)
        ),
    CONSTRAINT chk_notion_connections_duplicated_template_id_not_blank
        CHECK (duplicated_template_id IS NULL OR btrim(duplicated_template_id) <> ''),
    CONSTRAINT chk_notion_connections_request_id_not_blank
        CHECK (request_id IS NULL OR btrim(request_id) <> ''),
    CONSTRAINT chk_notion_connections_updated_at CHECK (updated_at >= created_at)
);
