ALTER TABLE content_source_connections
    ADD CONSTRAINT uk_content_source_connections_id_workspace UNIQUE (id, workspace_id);

CREATE TABLE notion_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    content_source_connection_id BIGINT NOT NULL,
    requested_by_member_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    total_page_count INTEGER,
    processed_page_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_notion_import_runs PRIMARY KEY (id),
    CONSTRAINT fk_notion_import_runs_connection
        FOREIGN KEY (content_source_connection_id, workspace_id)
        REFERENCES content_source_connections (id, workspace_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notion_import_runs_requester_membership
        FOREIGN KEY (workspace_id, requested_by_member_id)
        REFERENCES workspace_members (workspace_id, member_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notion_import_runs_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_notion_import_runs_status_timestamps
        CHECK (
            (status = 'PENDING' AND started_at IS NULL AND completed_at IS NULL)
            OR (status = 'RUNNING' AND started_at IS NOT NULL AND completed_at IS NULL)
            OR (status IN ('COMPLETED', 'FAILED') AND started_at IS NOT NULL AND completed_at IS NOT NULL)
        ),
    CONSTRAINT chk_notion_import_runs_total_page_count
        CHECK (total_page_count IS NULL OR total_page_count >= 0),
    CONSTRAINT chk_notion_import_runs_processed_page_count
        CHECK (processed_page_count >= 0),
    CONSTRAINT chk_notion_import_runs_page_counts
        CHECK (total_page_count IS NULL OR processed_page_count <= total_page_count)
);

CREATE UNIQUE INDEX uk_notion_import_runs_one_active
    ON notion_import_runs (content_source_connection_id)
    WHERE status IN ('PENDING', 'RUNNING');

CREATE INDEX idx_notion_import_runs_workspace_created
    ON notion_import_runs (workspace_id, created_at DESC);
