CREATE TABLE notion_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    notion_page_id VARCHAR(100) NOT NULL,
    parent_page_id BIGINT,
    title TEXT NOT NULL,
    markdown_content TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    notion_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_notion_pages PRIMARY KEY (id),
    CONSTRAINT uk_notion_pages_workspace_notion_page UNIQUE (workspace_id, notion_page_id),
    CONSTRAINT uk_notion_pages_id_workspace UNIQUE (id, workspace_id),
    CONSTRAINT fk_notion_pages_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES workspaces (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notion_pages_parent
        FOREIGN KEY (parent_page_id, workspace_id)
        REFERENCES notion_pages (id, workspace_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notion_pages_notion_page_id
        CHECK (BTRIM(notion_page_id) <> ''),
    CONSTRAINT chk_notion_pages_parent
        CHECK (parent_page_id IS NULL OR parent_page_id <> id),
    CONSTRAINT chk_notion_pages_position
        CHECK (position >= 0),
    CONSTRAINT chk_notion_pages_notion_url
        CHECK (BTRIM(notion_url) <> ''),
    CONSTRAINT chk_notion_pages_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_notion_pages_workspace_order
    ON notion_pages (workspace_id, position, id);
