# 로컬 데이터베이스
spring.datasource.url=jdbc:postgresql://localhost:5432/knot
spring.datasource.username=knot
spring.datasource.password=knot

# 로컬 GitHub OAuth App 설정
spring.security.oauth2.client.registration.github.client-id=Ov23liv91JtEK8iPdFc4
spring.security.oauth2.client.registration.github.client-secret=a2381c1a7735c55087b1338666601b6946585930
spring.security.oauth2.client.registration.github.scope=read:user

# 로컬 HTTP에서는 Secure cookie를 사용할 수 없습니다.
auth.jwt.secret=2q5Z9WntQ/xIHwrWVIuJfmBtjZwslmVRdo0FrZc3kqo=
auth.jwt.cookie-name=KNOT_ACCESS_TOKEN
auth.jwt.secure=false
